CREATE DATABASE wisher;
USE wisher;

CREATE TABLE IF NOT EXISTS ci_sessions (
	id VARCHAR(128) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    timestamp INT UNSIGNED DEFAULT 0 NOT NULL,
    data BLOB NOT NULL,
    KEY ci_sessions_timestamp(timestamp)
);

CREATE TABLE IF NOT EXISTS Users(
    UserId INT AUTO_INCREMENT NOT NULL,
    Username VARCHAR(40) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(UserId),
    INDEX (Email)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS WishList(
    ListId INT AUTO_INCREMENT NOT NULL,
	Title VARCHAR(100) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL,
    PRIMARY KEY(ListId),
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Priority(
    PriorityId INT AUTO_INCREMENT NOT NULL,
	PriorityTitle VARCHAR(100) NOT NULL,
    PRIMARY KEY(PriorityId)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS WishListItems(
    ItemId INT AUTO_INCREMENT NOT NULL,
	Title VARCHAR(100) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    Price DECIMAL(6,2) NOT NULL,
    Quantity INT NOT NULL,
    PriorityId INT NOT NULL,
    ListId INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL,
    PRIMARY KEY(ItemId),
    FOREIGN KEY (ListId) REFERENCES WishList(ListId),
    FOREIGN KEY (PriorityId) REFERENCES Priority(PriorityId)
)ENGINE = InnoDB;



